name: Test and Lint

on:
  push:
    branches:
      - master
  pull_request:
    branches: 
      - develop 
      - master 
env:
  PSQL_DATABASE_URL_DEVELOPMENT: ${{ secrets.PSQL_DATABASE_URL_DEVELOPMENT }}

jobs:
  docker:
    timeout-minutes: 10
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Start containers
      run: docker-compose -f "docker-compose.yml" up -d --build

    - name: Install node
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Install dependencies
      run: npm install

    - name: Run tests
      env:
        PSQL_DATABASE_URL_TEST: ${{ secrets.PSQL_DATABASE_URL_TEST }}
      run: npm run test

    - name: Run linter
      run: npm run lint

    - name: Stop containers
      if: always()
      run: docker-compose -f "docker-compose.yml" down